### ISSUE TITLE
Incorrect npm version on npmjs

### ISSUE THREAD

**Issue by adamsolomon1986** [margelo/react-native-worklets-core#102]
I tried installing this from npm and it says the package hasn't been updated for over 3 years (version 0.0.1-alpha). However, looking at the GitHub code, it looks like it was updated recently. How do I install this from GitHub directly?

**Comment by patras1** [comment]
+1

**Comment by patras1** [comment]
Try to run "npm i https://github.com/chrfalch/react-native-worklets"
I worked for me

**Comment by adamsolomon1986** [comment]
Thanks for your help, installing as your suggested worked.

@patras1 I keep getting 
`TypeError: Cannot read property 'createContext' of undefined`


```
import { Worklets } from 'react-native-worklets/src/types'

const fibonacci = (num) => {
  'worklet'
  if (num <= 1) return 1
  return fibonacci(num - 1) + fibonacci(num - 2)
}

export const workletTest = async () => {

 const context1 = Worklets.createContext('my-new-thread-1')
 alert('reated context')
  const worklet = Worklets.createRunInContextFn(fibonacci)
  alert("RUNNNING")
const result = await worklet(50)
console.warn(`Fibonacci of 50 is ${result}`)
}
```


Any idea why?

**Comment by mrousavy** [comment]
We just now published to npm; react-native-worklets-core
