### ISSUE TITLE
Can i use setInterval inside useWorklet?

### ISSUE THREAD

**Issue by devoren** [margelo/react-native-worklets-core#114]
Hello! I want to create a timer and I use useState and because of this the js thread frame rate drops to 55 and does not update to 60 fps. So I want to recreate this using worklets. Is it possible?

Current custom hook: 
```
export const useCountdown = (deadline: string) => {
	const countDownDate = useMemo(() => Date.parse(deadline), [deadline]);
	const [countDown, setCountDown] = useState(countDownDate - new Date().getTime());

	useEffect(() => {
		const interval = setInterval(() => {
			setCountDown(countDownDate - new Date().getTime());
		}, 1000);

		return () => clearInterval(interval);
	}, [countDownDate]);

	return getReturnValues(countDown);
};
```

**Comment by chrfalch** [comment]
This would neither be working well or be the recommended solution. What you're trying to do here seems like to move scheduling over to a separate thread and then move back into the JS thread 60 times per second to update state - I don't think this would help performance unfortunately.
