### ISSUE TITLE
How to use external libraries like RNFS or Axios in Worklet functions?

### ISSUE THREAD

**Issue by ninadjoshi20** [margelo/react-native-worklets-core#135]
I am trying to read a file and upload it using Axios in worklet functions. But its asking me to decorate the external library function with worklet keyword which cannot be done. Any workaround for this?

**Comment by kunal-d11** [comment]
I don't think using external library function in worklet function will work. Worklet functions are executed on different hermes runtime, to do this the function definition is copied. Adding `worklet` keyword helps in creating copy, thus if external library function does not have workletised function, it won't be copied and hence will not work. Correct me if I am wrong @mrousavy

**Comment by mrousavy** [comment]
Correct @kunal-d11 👍 

There's no reason to use RNFS in a Worklet. It is already async and ran on a separate native Thread.
