### ISSUE TITLE
Build failed after installing react-native-worklets-core version 0.2.2

### ISSUE THREAD

**Issue by Virajmakwana** [margelo/react-native-worklets-core#138]
I want to use this library for using in the frameprocessor of reactnative to get the frames like below.

```
const frameProcessor = useFrameProcessor((frame) => {
  'worklet'
  console.log(`Frame: ${frame.width}x${frame.height} (${frame.pixelFormat})`)
}, [])
```

but after installing the package I am getting the below error and build gets failed so not able to start the project.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\skia\node_modules\react-native-worklets-core\android\build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':react-native-worklets-core'.
Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.

Reactnative version 
0.68.2
How can i solve this error?

**Comment by mrousavy** [comment]
Add the `hermesEnabled` property to your app.

But to be honest I don't know if 0.68 will work. You might need to upgrade to RN 0.71.+
