### ISSUE TITLE
Android build error on RN < 0.71

### ISSUE THREAD

**Issue by levepic** [margelo/react-native-worklets-core#171]
Build error on RN < 0.71

`
> Could not resolve all task dependencies for configuration ':react-native-worklets-core:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :react-native-worklets-core
   > Could not find com.facebook.react:hermes-android:.
     Required by:
         project :react-native-worklets-core
`

It works from RN 0.71 although it's cumbersome to upgrade some projects just because of this. Is there a solution? Seems like something minor.

**Comment by MartinTorresCh** [comment]
any solution?

**Comment by mrousavy** [comment]
RN 0.71 is no longer supported by react-native-worklets-core. Please upgrade RN, or try to downgrade to an older react-native-worklets-core version, but I don't remember which one.
