### ISSUE TITLE
Error with version 1.1.1: system/frame-processors-unavailable: Frame Processors are not available

### ISSUE THREAD

**Issue by christophemenager** [margelo/react-native-worklets-core#172]
Tested on:
- iOS 17.2
- expo: 50.0.17
- react-native-worklets-core: 1.1.1
- react-native-vision-camera: 3.9.2

The build is successful but there is an error at launch time
```
LOG  Loading react-native-worklets-core...
LOG  Worklets loaded successfully
ERROR  system/frame-processors-unavailable: Frame Processors are not available, react-native-worklets-core is not installed!, js engine: hermes
```

I switched back to version 0.5.0 and the error disappeared.

**Comment by mrousavy** [comment]
Compatibility: 

| react-native-vision-camera | 3.x.x | 4.x.x |
|----------------------------|-------|-------|
| react-native-worklets-core | 0.x.x | 1.x.x |
