### ISSUE TITLE
'ReactCommon/RCTBlockGuard.h' file not found

### ISSUE THREAD

**Issue by kaancembertas** [margelo/react-native-worklets-core#181]
I get 'ReactCommon/RCTBlockGuard.h' file not found error when I add the dependency "react-native-worklets-core" in order to use "react-native-vision-camera"'s video processors.

**Comment by FilipiRafael** [comment]
got it @kaancembertas, but what did you do to solve it? Did you just remove this dependency, update its version or something like that?

**Comment by kaancembertas** [comment]
@FilipiRafael just update the package to latest version

**Comment by FilipiRafael** [comment]
I did it @kaancembertas but the error is still there, did you update the react-native-vision-camera too?

**Comment by kaancembertas** [comment]
@FilipiRafael Yeah also updated vision camera
