### ISSUE TITLE
useWorklet throws "anonymous" is not a worklet

### ISSUE THREAD

**Issue by JRolfBPS** [margelo/react-native-worklets-core#190]
I have tried testing this library with code similar to the example code from this repository.
I built a react native functional component that uses the useWorklet hook in order to create a basic worklet:

```javascript
const testWorklet = useWorklet("default", (name: string) => {
    "worklet";

    console.log("Hello, " + name);

    return "Return " + name;
  } )
```

When I run the app I encounter the following error:
<img width="326" alt="image" src="https://github.com/margelo/react-native-worklets-core/assets/94978056/67414e1f-96e6-4b6b-8a20-41e61e0d558b">

I installed the package using yarn and added the related plugin in my babel.config.js.
Maybe this is related to [PR #187](https://github.com/margelo/react-native-worklets-core/pull/187)?

**Comment by ceu** [comment]
same, there have any solution ?

**Comment by nmajumder12** [comment]
@JRolfBPS @ceu  https://github.com/margelo/react-native-worklets-core/pull/194

**Comment by ceu** [comment]
thanks, Can I ask when you will be able to push the new version? @nmajumder12

**Comment by ceu** [comment]
Now wait for the version that fixes the bug!

**Comment by hannojg** [comment]
The fix is deployed in version https://github.com/margelo/react-native-worklets-core/releases/tag/v1.3.3
