### ISSUE TITLE
jsi:Runtime cann't  execute in thread

### ISSUE THREAD

**Issue by scorpionfeng** [margelo/react-native-worklets-core#193]
when use the code such as below in
...
Thread t1([&runTime,argument,resolver](){
argument.asObject(runtime).asFunction(runtime).call(runtime,nullptr,0)//  this line will crash 
}).deteach()

Is there any other approach to fix the  crash ?

**Comment by mrousavy** [comment]
I don't think this has anything to do with react-native-worklets-core.
