### ISSUE TITLE
IOS Build crash 

### ISSUE THREAD

**Issue by xi3793-rpareek** [margelo/react-native-worklets-core#201]
unsigned long std::__1::__tree<std::__1::__value_type<void*, RNWorklet::JsiWorkletContext*>, std::__1::__map_value_compare<void*, std::__1::__value_type<void*, RNWorklet::JsiWorkletContext*>, std::__1::less<void*>, true>, std::__1::allocator<std::__1::__value_type<void*, RNWorklet::JsiWorkletContext*>>>::__erase_unique<void*>(void* const&)

Version detail :- 
"react-native-worklets-core": "0.3.0",
"react-native": "0.72.3",
"react-native-vision-camera": "4.0.0"

Firebase Stack-trace :- 

Crashed: com.facebook.react.ExitAppQueue
0  mobileProject                      0x69d058 unsigned long std::__1::__tree<std::__1::__value_type<void*, RNWorklet::JsiWorkletContext*>, std::__1::__map_value_compare<void*, std::__1::__value_type<void*, RNWorklet::JsiWorkletContext*>, std::__1::less<void*>, true>, std::__1::allocator<std::__1::__value_type<void*, RNWorklet::JsiWorkletContext*>>>::__erase_unique<void*>(void* const&) + 403 (operations.h:403)
1  mobileProject                      0x69b588 RNWorklet::JsiWorkletContext::~JsiWorkletContext() + 67 (WKTJsiWorkletContext.cpp:67)
2  mobileProject                      0x2184c std::__1::shared_ptr<RNWorklet::JsiWorkletContext>::~shared_ptr[abi:ue170006]() + 215 (shared_ptr.h:215)
3  libsystem_c.dylib              0x18cfc __cxa_finalize_ranges + 476
4  libsystem_c.dylib              0x18acc exit + 32
5  mobileProject                      0x18c54 @objc ExitAppModule.init() + 4299476052 (<compiler-generated>:4299476052)
6  CoreFoundation                 0x31c84 __invoking___ + 148
7  CoreFoundation                 0x31710 -[NSInvocation invoke] + 428
8  CoreFoundation                 0x31538 -[NSInvocation invokeWithTarget:] + 64
9  mobileProject                      0x4d1dc4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
10 mobileProject                      0x4d3e18 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 197 (RCTNativeModule.mm:197)
11 mobileProject                      0x4d3a68 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 304 (optional:304)
12 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
13 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
14 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
15 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
16 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
17 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
18 libsystem_pthread.dylib        0x1f20 _pthread_wqthread + 288
19 libsystem_pthread.dylib        0x1fc0 start_wqthread + 8

**Comment by akhilduggimpudi** [comment]
Hi, is there any update on this issue. Many users are facing this for IOS, as it is getting registered on crashlytics.

Version detail :-
"react-native-worklets-core": "1.3.3",
"react-native": "0.74.3",
"react-native-vision-camera": "4.5.0"

**Comment by kiet-ap** [comment]
Yes, I still don’t know why this issue happens. 😿

**Comment by mrousavy** [comment]
We need a reproduction for this issue.
