### ISSUE TITLE
Support for offloading tasks which use imported JS libraries?

### ISSUE THREAD

**Issue by mr-tm** [margelo/react-native-worklets-core#202]
Currently it seems like we can just use our own functions with 'worklet' statement. Are there any plans to support imported libraries?
Eg. Passing JS instantiated objects to some of turf.js functions which are executed on another thread.
```
function nearest(targetPoint, points){
  'worklet'
  return turf.nearestPoint(targetPoint, points);
}
```

**Comment by hannojg** [comment]
That not really possible to add from the library side. You'd need to look into "workletizng" the turf.js code yourself and use that. If it's a pure JS library it should be possible (ie. get the library code and mark everything as `"worklet"`)
