### ISSUE TITLE
'ReactCommon/RCTTurboModule.h' file not found

### ISSUE THREAD

**Issue by wogno** [margelo/react-native-worklets-core#216]
I faced this issue at react native 0.75
![Capture d’écran 2024-09-18 à 21 24 55](https://github.com/user-attachments/assets/bd3d55f0-f0a4-4c92-ac8b-848e7935619e)
![Capture d’écran 2024-09-18 à 21 25 07](https://github.com/user-attachments/assets/44893bdb-9831-4df2-bebd-b3d9eced7d47)

**Comment by adriaanslechten** [comment]
Yes, i had the same. Weird enough only when archiving.

Manually replacing this with `#import "RCTTurboModule.h"` patched this for me. Not ideal but good enough to get unblocked.

**Comment by wogno** [comment]
@adriaanslechten  Thanks it worked.

**Comment by marwan362** [comment]
any fix please ?

**Comment by hasanalicansu** [comment]
Also I am getting this error in version 1.4.0. 

```
    "react-native": "0.75.4",
    "react-native-worklets-core": "^1.4.0",
```

**Comment by mrousavy** [comment]
fixed in https://github.com/margelo/react-native-worklets-core/commit/6918abd77bb1926087186d3bc06f01b7faadb902. Requires RN 0.74 or higher

**Comment by Kmannam-sos** [comment]
> Yes, i had the same. Weird enough only when archiving.
> 
> Manually replacing this with `#import "RCTTurboModule.h"` patched this for me. Not ideal but good enough to get unblocked.
> 
> I think there is a PR open to fix this: [link](https://github.com/margelo/react-native-worklets-core/pull/214/files)

Fixed the issue. Thank you @adriaanslechten adriaanslechte

**Comment by usamaabutt** [comment]
I was using version `"react-native-worklets-core": "^1.3.3",` I just removed `^` and installed the dependencies and pods again. It starts working.

**Comment by andrewoodleyjr** [comment]
@adriaanslechten wild that it worked.

**Comment by monilraycha** [comment]
> Yes, i had the same. Weird enough only when archiving.
> 
> Manually replacing this with `#import "RCTTurboModule.h"` patched this for me. Not ideal but good enough to get unblocked.
> 
> I think there is a PR open to fix this: [link](https://github.com/margelo/react-native-worklets-core/pull/214/files)

In which file we need to replace it ?

**Comment by fujadev** [comment]
Not working for me
