### ISSUE TITLE
Integrate into other module

### ISSUE THREAD

**Issue by tomh4** [margelo/react-native-worklets-core#219]
Hello,
I have a little module that would greatly benefit from using worklets,
but I am unsure on how to integrate it.

I am not using babel to build to module, but I guess that is needed and for the rest use it as in a normal js application?

Keep up the great work!

**Comment by mrousavy** [comment]
here's a guide for that: https://github.com/margelo/react-native-worklets-core/blob/main/docs/USAGE.md#integration
